#!/bin/bash

if [ "$#" -eq 0 ]; then
 commit_message="-"
else
 commit_message="$1"
fi

shift
while [ "$#" -gt 0 ]; do
    commit_message="$commit_message $1"
    shift
done

git add .

git commit -m "$commit_message"

git push
